# Site settings
title: "Tokyo & Seoul Venture"
description: "The Tokyo & Seoul Venture by Michael Rurka. Love you mum + papa."
baseurl: "/tokyo" # the subpath of your site, e.g. /blog/
url: "http://mrurka.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown