# Site settings
title: Tokyo / Seoul
email: michael@rurkadesign.com
description: "XXX"
baseurl: "/tokyo" # the subpath of your site, e.g. /blog/
url: "http://mrurka.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown